### ISSUE TITLE
Support for Notebook widget

### ISSUE THREAD

**Issue by acoplu** [ikus060/tkvue#1]
Hello,
It seems like there's no support for the Notebook widget, which could actually be quite useful. Without it, creating tabbed windows is pretty tricky. Adding support for this widget would make things a lot easier and more user-friendly.

**Comment by ikus060** [comment]
Hello Acoplu,

I'm not planning to work on Tkvue for the time being. I invite your to make a copy of Tkvue and implement the notebook widget support. It's relatively easy to add new widget in Tkvue.
